name = "freegameping"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# KV Namespace f√ºr gespeicherte Spiele
kv_namespaces = [
  { binding = "POSTED_GAMES", id = "0b9bb022854d4dfda1e014c7afee79e8", preview_id = "b90d744975f24fe9ac7c1274ac3911ca" },
  { binding = "GUILD_CONFIGS", id = "3ac68e8a834e4a2fb8742d5bacd7ff5b", preview_id = "14c2165b62d34932b90038e18ce7fefc" }
]

# Cron Trigger
[triggers]
# Schedule cron triggers:
# - Everyday at 15:05 (UTC)
# - Every 3 hours
crons = ["0 */3 * * *", "5 15 * * *"]