name = "freegameping"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

# KV Namespace f√ºr gespeicherte Spiele
kv_namespaces = [
  { binding = "POSTED_GAMES", id = "0b9bb022854d4dfda1e014c7afee79e8" },
  { binding = "GUILD_CONFIGS", id = "3ac68e8a834e4a2fb8742d5bacd7ff5b" }
]

# Cron Trigger
[triggers]
# Schedule cron triggers:
# - Everyday at 15:05 (UTC)
# - Every 3 hours
crons = ["0 */3 * * *", "5 15 * * *"]